M48
; DRILL file {KiCad (7.0.0)} date Fri Dec  8 15:04:05 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-08T15:04:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
%
G90
G05
T1
X113.15Y-138.875
X119.95Y-138.875
T2
X154.515Y-138.24
X159.365Y-138.24
T3
X154.215Y-141.27
X159.665Y-141.27
T0
M30
